version: 2
updates:
  - package-ecosystem: "github-actions""
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      gh:
        patterns:
        - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      py-dependencies:
        patterns:
        - "*"

