#!/usr/bin/python

from visitors import visit_sql
from state import State, Counter
from argparse import ArgumentParser, BooleanOptionalAction
import sys

parser = ArgumentParser(description='Spot vulnerabilities in PostgreSQL SQL scripts')
parser.add_argument("-a","--append",dest="append",action="store_true",default=False,help="append files before checking")
parser.add_argument("--proc-without-search-path",metavar="PROC",dest="proc_without_search_path",action="append",default=list(),help="functions without explicit search_path")
parser.add_argument("--summary-only",dest="summary_only",action="store_true",default=False,help="only print number of errors, warnings and unknowns")
parser.add_argument("--plpgsql", action=BooleanOptionalAction, default=True, help="Analyze PLpgSQL code")
parser.add_argument('files',metavar='FILE',type=str,nargs='*',help='file to check for vulnerabilities')

args = parser.parse_args()

counter = Counter(args)

if args.files:
  if args.append:
    # treat all files as single unit during processing
    data = "\n".join([open(f).read() for f in args.files])
    visit_sql(State(counter), data)

  else:
    # process each file individually
    for f in args.files:
      if len(args.files) > 1:
        print("\n{}\n".format(f))
      data = open(f).read()

      visit_sql(State(counter), data)

else:
  # read from stdin
  data = sys.stdin.read()

  visit_sql(State(counter), data)

print(counter)

if not counter.is_clean():
  sys.exit(1)

